# Generated by Django 5.0.2 on 2025-03-25 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='departement_id',
        ),
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='entite_id',
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils', to='users.departement'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='entite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils', to='users.entite'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('enseignant', 'Enseignant'), ('responsable_classe', 'Responsable de Classe'), ('directeur_academique', 'Directeur Academique'), ('controleur', 'Controleur'), ('chef_département', 'Chef de Département')], max_length=50),
        ),
    ]
