# Generated by Django 5.0.2 on 2025-04-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classe_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='est_tronc_commun',
            field=models.BooleanField(default=False, help_text='Indique si la classe est un tronc commun pour plusieurs formations.'),
        ),
    ]
