# Generated by Django 5.0.2 on 2025-04-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classe_est_tronc_commun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='est_tronc_commun',
            field=models.BooleanField(default=False, verbose_name='Est-ce une classe de tronc commun ?'),
        ),
    ]
