# Generated by Django 5.0.2 on 2025-03-27 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('cours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('duree', models.DurationField(editable=False)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé')], default='brouillon', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='classes.classe')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='cours.cours')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_enseignant', to=settings.AUTH_USER_MODEL)),
                ('responsable_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('validation', 'Validation'), ('annulation', 'Annulation')], max_length=20)),
                ('validee_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_validations', to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_validations', to='seances.seance')),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
    ]
