# Generated by Django 5.0.2 on 2025-04-14 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
        ('users', '0002_remove_profilutilisateur_departement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='entite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='users.entite'),
        ),
    ]
