# Generated by Django 5.0.2 on 2025-03-26 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
        ('users', '0002_remove_profilutilisateur_departement_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='users.departement'),
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
    ]
